export const games = [
    {
        id: 1,
        nombre: "APEX Legends",
        creador: "Electronic Arts",
        esrb: "13+ Teen",
        precio: "350",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/01.jpg",
        stock: 28,
        categoria: "battle_royale",
        tiempo: 4,
        puntuacion: 80,
        detalles:
            "Conquista con el personaje en Apex Legends ™, un juego de batalla gratuito de batalla real en el que los legendarios rivales luchan por la gloria, la fama y la fortuna en los márgenes de la Frontera. Elija de una lista de personajes únicos y experimente la próxima evolución de battle royale.",
        video: "https://www.youtube.com/watch?v=-50ZwgIrJtg",
    },
    {
        id: 2,
        nombre: "CONTROL",
        creador: "505 Games",
        esrb: "17+ Mature",
        precio: "400",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/02.jpg",
        stock: 22,
        categoria: "aventura",
        tiempo: 6,
        puntuacion: 84,
        detalles:
            "Control es el nuevo videojuego de acción en tercera persona desarrollado por Remedy Entertainment, creadores de la serie Max Payne y del aclamado Alan Wake. Disponible en PlayStation 4, Xbox One y PC, el juego propone una experiencia paranormal en la que el jugador deberá descubrir los misterios de una agencia gubernamental estadounidense.",
        video: "https://www.youtube.com/watch?v=zZ93KAQgE3k",
    },
    {
        id: 3,
        nombre: "Cyberpunk 2077",
        creador: "CD PROKECT RED",
        esrb: "17+ Mature",
        precio: "560",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/03.jpg",
        stock: 8,
        categoria: "mundo_abierto",
        tiempo: 23,
        puntuacion: 73,
        detalles:
            "Cyberpunk 2077 es una historia de acción y aventura en mundo abierto ambientada en Night City, una megalópolis obsesionada con el poder, el glamur y la modificación corporal. Tu personaje es V, un mercenario que persigue un implante único que permite alcanzar la inmortalidad. Podrás personalizar las mejoras cibernéticas, las habilidades y el estilo de juego del personaje para dar forma a un mundo y a una historia que depende de tus decisiones.",
        video: "https://www.youtube.com/watch?v=F3YglDIEqoI",
    },
    {
        id: 4,
        nombre: "Days Gone",
        creador: "Sony Interactive Entertainment",
        esrb: "17+ Mature",
        precio: "580",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/04.jpg",
        stock: 45,
        categoria: "mundo_abierto",
        tiempo: 14,
        puntuacion: 74,
        detalles:
            "Days Gone es un videojuego de acción y horror de supervivencia ambientado en un entorno de mundo abierto, post-apocalíptico y jugado desde una perspectiva en tercera persona. El jugador toma el control del protagonista del juego, Deacon St. John (Samuel Witwer), un cazarrecompensas que prefiere vivir una vida peligrosa a campo abierto que esconderse en campamentos en lo más profundo del bosque",
        video: "https://www.youtube.com/watch?v=f0tPBXEfXzs",
    },
    {
        id: 5,
        nombre: "Doom",
        creador: "Bethesda Softworks",
        esrb: "17+ Mature",
        precio: "600",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/05.jpg",
        stock: 16,
        categoria: "fps",
        tiempo: 10,
        puntuacion: 85,
        detalles:
            "Los jugadores toman el papel de un marine espacial sin nombre mientras lucha contra las fuerzas demoníacas del infierno que han sido desatadas por la Unión Aerospace Corporation en un planeta colonizado en el futuro, Marte. La jugabilidad vuelve a un ritmo más rápido con más niveles abiertos, más cerca de los primeros dos juegos que el enfoque más lento de terror de supervivencia de Doom 3.",
        video: "https://www.youtube.com/watch?v=l5XQ4zABINA",
    },
    {
        id: 6,
        nombre: "Dark Souls",
        creador: "Bandai Namco Entertainment",
        esrb: "17+ Mature",
        precio: "480",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/06.jpg",
        stock: 10,
        categoria: "rpg",
        tiempo: 48,
        puntuacion: 89,
        detalles:
            "El juego tiene lugar en los últimos días de la Edad del Fuego, la cual comenzó tras la derrota de los Dragones de Piedra que anteriormente reinaban el mundo. Durante esta época el mundo era un lugar oscuro y lúgubre habitado solamente por una raza inmortal de dragones cuya capacidad de prolongar su vida eternamente provenía de sus escamas pétreas.",
        video: "https://www.youtube.com/watch?v=2_w0mNRhNSc",
    },
    {
        id: 7,
        nombre: "HORIZON Forbidden west",
        creador: "Sony Computer Entertainment",
        esrb: "13+ Teen",
        precio: "380",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/07.jpg",
        stock: 23,
        categoria: "rpg",
        tiempo: 20,
        puntuacion: 86,
        detalles: "",
        video: "https://www.youtube.com/watch?v=InoAU5wUFcE",
    },
    {
        id: 8,
        nombre: "FORZA Horizon 4",
        creador: "Microsoft Studios",
        esrb: "Everyone",
        precio: "900",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/08.jpg",
        stock: 14,
        categoria: "carreras",
        tiempo: 13,
        puntuacion: 90,
        detalles: "",
        video: "https://www.youtube.com/watch?v=MHKqOVAjdgw",
    },
    {
        id: 9,
        nombre: "Call of Duty Vanguard",
        creador: "Activision Blizzard",
        esrb: "17+ Mature",
        precio: "600",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/09.jpg",
        stock: 19,
        categoria: "fps",
        tiempo: 12,
        puntuacion: 73,
        detalles: "",
        video: "https://www.youtube.com/watch?v=zdVk4hHQTn0",
    },
    {
        id: 10,
        nombre: "Devil May Cry 5",
        creador: "Capcom",
        esrb: "17+ Mature",
        precio: "700",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/10.jpg",
        stock: 15,
        categoria: "aventura",
        tiempo: 9,
        puntuacion: 88,
        detalles: "",
        video: "https://www.youtube.com/watch?v=CMjNBDq6lnQ",
    },
    {
        id: 11,
        nombre: "STAR WARS Jedi Fallen Order",
        creador: "Respawn Entertainment",
        esrb: "13+ Teen",
        precio: "550",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/11.jpg",
        stock: 3,
        categoria: "aventura",
        tiempo: 9,
        puntuacion: 80,
        detalles: "",
        video: "https://www.youtube.com/watch?v=lw3tTKYGwr8",
    },
    {
        id: 12,
        nombre: "UNCHARTED 4",
        creador: "Naughty Dog",
        esrb: "13+ Teen",
        precio: "600",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/12.jpg",
        stock: 9,
        categoria: "aventura",
        tiempo: 8,
        puntuacion: 93,
        detalles: "",
        video: "https://www.youtube.com/watch?v=34GJ9ZMAKqA",
    },
    {
        id: 13,
        nombre: "SEKIRO Shadows die twice",
        creador: "FromSoftware",
        esrb: "17+ Mature",
        precio: "900",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/13.jpg",
        stock: 21,
        categoria: "aventura",
        tiempo: 15,
        puntuacion: 90,
        detalles: "",
        video: "https://www.youtube.com/watch?v=e8iGRmFCRQk",
    },
    {
        id: 14,
        nombre: "Little Nightmares II",
        creador: "Tarsier Studios",
        esrb: "13+ Teen",
        precio: "520",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/14.jpg",
        stock: 34,
        categoria: "plataforma",
        tiempo: 6,
        puntuacion: 82,
        detalles: "",
        video: "https://www.youtube.com/watch?v=urgBaLe4w-0",
    },
    {
        id: 15,
        nombre: "HITMAN 3 Contracts",
        creador: "Square Enix",
        esrb: "18+ Adults Only",
        precio: "580",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/15.jpg",
        stock: 65,
        categoria: "fps",
        tiempo: 1,
        puntuacion: 77,
        detalles: "",
        video: "https://www.youtube.com/watch?v=1PpLijU1l9M",
    },
    {
        id: 16,
        nombre: "It takes two",
        creador: "Hazelight",
        esrb: "Everyone",
        precio: "600",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/16.jpg",
        stock: 12,
        categoria: "aventura",
        tiempo: 10,
        puntuacion: 89,
        detalles: "",
        video: "https://www.youtube.com/watch?v=s-i_ys7VauE",
    },
    {
        id: 17,
        nombre: "MINECRAFT",
        creador: "Mojang",
        esrb: "Everyone",
        precio: "450",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/17.jpg",
        stock: 30,
        categoria: "mundo_abierto",
        tiempo: 26,
        puntuacion: 83,
        detalles: "",
        video: "https://www.youtube.com/watch?v=kobFwRJsvQE",
    },
    {
        id: 18,
        nombre: "Metal Gear Solid V",
        creador: "Konami Digital Entertainment",
        esrb: "Not rated",
        precio: "700",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/18.jpg",
        stock: 18,
        categoria: "fps",
        tiempo: 4,
        puntuacion: 80,
        detalles: "",
        video: "https://www.youtube.com/watch?v=L5SsuDFu_ys",
    },
    {
        id: 19,
        nombre: "The Last of Us Part II",
        creador: "Naughty Dog",
        esrb: "The Last Of Us",
        precio: "690",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/19.jpg",
        stock: 9,
        categoria: "aventura",
        tiempo: 11,
        puntuacion: 93,
        detalles: "",
        video: "https://www.youtube.com/watch?v=VSLSvEjDm5s",
    },
    {
        id: 20,
        nombre: "Portal 2",
        creador: "Valve Software",
        esrb: "Everyone",
        precio: "450",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/20.jpg",
        stock: 12,
        categoria: "fps",
        tiempo: 11,
        puntuacion: 95,
        detalles: "",
        video: "https://www.youtube.com/watch?v=e0jEKr75ORw",
    },
    {
        id: 21,
        nombre: "ASSASIN´S CREED Valhalla",
        creador: "Ubisoft Montreal",
        esrb: "17+ Mature",
        precio: "800",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/21.jpg",
        stock: 19,
        categoria: "aventura",
        tiempo: 12,
        puntuacion: 82,
        detalles: "",
        video: "https://www.youtube.com/watch?v=eARa4PZn_aE",
    },
    {
        ////////////////////////////**ACTUALIZADO HASTA ACA**////////////////////////////
        id: 22,
        nombre: "BATMAN Arkham City",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/22.jpg",
        stock: 43,
        categoria: "aventura",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=fQsXjKVSOgU",
    },
    {
        id: 23,
        nombre: "BACK4BLOOD",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/23.jpg",
        stock: 12,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=tKlFJbyUsoo",
    },
    {
        id: 24,
        nombre: "Call of Duty WWII",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/24.jpg",
        stock: 19,
        categoria: "fps",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=wrf3kArb3qU",
    },
    {
        id: 25,
        nombre: "ASSASIN´S CREED II",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/25.jpg",
        stock: 21,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=O7-IYE4B6lE",
    },
    {
        id: 26,
        nombre: "CUPHEAD Don´t Deal With the Devil",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/26.jpg",
        stock: 13,
        categoria: "plataforma",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=D-1n15aIgsE",
    },
    {
        id: 27,
        nombre: "DEATHLOOP",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/27.jpg",
        stock: 23,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=4-J9dP4qoZM",
    },
    {
        id: 28,
        nombre: "FIFA 21",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/28.jpg",
        stock: 19,
        categoria: "deportes",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=GBmhu8YlHNk",
    },
    {
        id: 29,
        nombre: "FARCRY 6",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/29.jpg",
        stock: 40,
        categoria: "mundo_abierto",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=tSDMwngdkF4",
    },
    {
        id: 30,
        nombre: "DOTA2",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/30.jpg",
        stock: 50,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=txFdVbDbcjk",
    },
    {
        id: 31,
        nombre: "ASSASIN´S CREED Odyssey",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/31.jpg",
        stock: 11,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=Asy_p4xStbk",
    },
    {
        id: 32,
        nombre: "CALL OF DUTY Modern Warfare",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/32.jpg",
        stock: 16,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=Scs7_H2qPq4",
    },
    {
        id: 33,
        nombre: "DOOM Eternal",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/33.jpg",
        stock: 12,
        categoria: "fps",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=-fsz6b3IBJY",
    },
    {
        id: 34,
        nombre: "Death Stranding",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/34.jpg",
        stock: 10,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=2nj9Ub32ILs",
    },
    {
        id: 35,
        nombre: "COUNTER STRIKE Global Offensive",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/35.jpg",
        stock: 8,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=edYCtaNueQY",
    },
    {
        id: 36,
        nombre: "GRAND THEFT AUTO San Andreas",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/36.jpg",
        stock: 56,
        categoria: "mundo_abierto",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=_rgp0XDH7yc",
    },
    {
        id: 37,
        nombre: "God of War",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/37.jpg",
        stock: 32,
        categoria: "aventura",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=AN3jEjjcZ-k",
    },
    {
        id: 38,
        nombre: "The Last of Us",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/38.jpg",
        stock: 55,
        categoria: "aventura",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=Do8gBW2oy_c",
    },
    {
        id: 39,
        nombre: "The Walking Death",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/39.jpg",
        stock: 32,
        categoria: "aventura",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=czgmQ8e7aTY",
    },
    {
        id: 40,
        nombre: "GRAND THEFT AUTO V",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/40.jpg",
        stock: 18,
        categoria: "mundo_abierto",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=2S4O8Ea6M9Y",
    },
    {
        id: 41,
        nombre: "Ghost of Tsushima",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/41.jpg",
        stock: 11,
        categoria: "aventura",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=jT9edKarhc8",
    },
    {
        id: 42,
        nombre: "HALF LIFE Alyx",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/42.jpg",
        stock: 19,
        categoria: "fps",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=O2W0N3uKXmo",
    },
    {
        id: 43,
        nombre: "SIMS 4",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/43.jpg",
        stock: 36,
        categoria: "simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=-ThjInNhEe4",
    },
    {
        id: 44,
        nombre: "Returnal",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/44.jpg",
        stock: 35,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=6VaVQxVWLMY",
    },
    {
        id: 45,
        nombre: "RESIDENT EVIL Village",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/45.jpg",
        stock: 30,
        categoria:
            "fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=ztj8fv6Ttp8",
    },
    {
        id: 46,
        nombre: "THE WITCHER Wild Hunt",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/46.jpg",
        stock: 45,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=c-OUdVkWnP8",
    },
    {
        id: 47,
        nombre: "HORIZON Zero Dawn",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/47.jpg",
        stock: 12,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=_BvZvkT5QHw",
    },
    {
        id: 48,
        nombre: "HALO Infinite",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/48.jpg",
        stock: 19,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=oMM0-hGwUE4",
    },
    {
        id: 49,
        nombre: "Enter the Gungion",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/49.jpg",
        stock: 17,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=BZSETJKBH5c",
    },
    {
        id: 50,
        nombre: "LIFE IS STRANGE",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/50.jpg",
        stock: 54,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=w6nf9lVKeuI",
    },
    {
        id: 51,
        nombre: "LIFE IS STRANGE True Colors",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/51.jpg",
        stock: 23,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=DJCskFcMeQM",
    },
    {
        id: 52,
        nombre: "HUMANKIND",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/52.jpg",
        stock: 45,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=c_dMvqak9o0",
    },
    {
        id: 53,
        nombre: "RESIDENT EVIL 2",
        creador: "",
        esrb: "",
        precio: "",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/53.jpg",
        stock: 23,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=AA4fRUp3Ono",
    },
    {
        id: 54,
        nombre: "TOMB RAIDER",
        creador: "",
        esrb: "",
        precio: "316",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/54.jpg",
        stock: 36,
        categoria:
            "mundo_abierto fps aventura battle_royale carreras fantasia plataforma deportes simulacion",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=H5hFiItax4U",
    },
    {
        id: 55,
        nombre: "SPIDER MAN Miles Morales",
        creador: "",
        esrb: "",
        precio: "250",
        imagen: "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/55.jpg",
        stock: 35,
        categoria: "aventura",
        tiempo: 72,
        puntuacion: 7.2,
        detalles: "",
        video: "https://www.youtube.com/watch?v=Q3kfF3XNzw8",
    },
];
