export const games = [
  {
    id: 1,
    nombre: "APEX Legends",
    creador: "EA",
    esrb: "T",
    precio: "350",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/01.jpg",
    stock: 28,
    categoria: "Battle Royale",
    tiempo: 72,
    puntuacion: 72,
    detalles:
      "Conquista con el personaje en Apex Legends ™, un juego de batalla gratuito * de batalla real en el que los legendarios rivales luchan por la gloria, la fama y la fortuna en los márgenes de la Frontera. Elija de una lista de personajes únicos y experimente la próxima evolución de battle royale.",
    video: "https://www.youtube.com/watch?v=-50ZwgIrJtg",
  },
  {
    id: 2,
    nombre: "CONTROL",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/02.jpg",
    stock: 2,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 3,
    nombre: "Cyberpunk 2077",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/03.jpg",
    stock: 8,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 4,
    nombre: "Days Gone",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/04.jpg",
    stock: 45,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 5,
    nombre: "Doom",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/05.jpg",
    stock: 16,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 6,
    nombre: "Dark Souls",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/06.jpg",
    stock: 10,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 7,
    nombre: "HORIZON Forbidden west",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/07.jpg",
    stock: 23,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 8,
    nombre: "FORZA Horizon 4",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/08.jpg",
    stock: 14,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 9,
    nombre: "Call of Duty Vanguard",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/09.jpg",
    stock: 19,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 10,
    nombre: "Devil May Cry 5",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/10.jpg",
    stock: 15,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 11,
    nombre: "STAR WARS Jedi Fallen Order",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/11.jpg",
    stock: 3,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 12,
    nombre: "UNCHARTED 4",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/12.jpg",
    stock: 9,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 13,
    nombre: "SEKIRO Shadows die twice",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/13.jpg",
    stock: 21,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 14,
    nombre: "Little Nightmares II",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/14.jpg",
    stock: 34,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 15,
    nombre: "HITMAN Contracts",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/15.jpg",
    stock: 65,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 16,
    nombre: "It takes two",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/16.jpg",
    stock: 12,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 17,
    nombre: "MINECRAFT",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/17.jpg",
    stock: 30,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 18,
    nombre: "Metal Gear Solid V",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/18.jpg",
    stock: 18,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 19,
    nombre: "The Last of Us Part II",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/19.jpg",
    stock: 9,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 20,
    nombre: "Portal 2",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/20.jpg",
    stock: 12,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 21,
    nombre: "ASSASIN´S CREED Valhalla",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/21.jpg",
    stock: 19,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 22,
    nombre: "BATMAN Arkham City",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/22.jpg",
    stock: 43,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 23,
    nombre: "BACK4BLOOD",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/23.jpg",
    stock: 12,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 24,
    nombre: "Call of Duty WWII",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/24.jpg",
    stock: 19,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 25,
    nombre: "ASSASIN´S CREED II",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/25.jpg",
    stock: 21,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 26,
    nombre: "CUPHEAD Don´t Deal With the Devil",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/26.jpg",
    stock: 13,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 27,
    nombre: "DEATHLOOP",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/27.jpg",
    stock: 23,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 28,
    nombre: "FIFA 21",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/28.jpg",
    stock: 19,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 29,
    nombre: "FARCRY 6",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/29.jpg",
    stock: 40,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 30,
    nombre: "DOTA2",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/30.jpg",
    stock: 50,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 31,
    nombre: "ASSASIN´S CREED Odyssey",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/31.jpg",
    stock: 11,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 32,
    nombre: "ASSASIN´S CREED Odyssey",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/32.jpg",
    stock: 16,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 33,
    nombre: "DOOM Eternal",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/33.jpg",
    stock: 12,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 34,
    nombre: "Death Stranding",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/34.jpg",
    stock: 10,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 35,
    nombre: "Death Stranding",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/35.jpg",
    stock: 8,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 36,
    nombre: "GRAND THEFT AUTO San Andreas",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/36.jpg",
    stock: 56,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 37,
    nombre: "God of War",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/37.jpg",
    stock: 32,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 38,
    nombre: "The Last of Us",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/38.jpg",
    stock: 55,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 39,
    nombre: "The Walking Death",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/39.jpg",
    stock: 32,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 40,
    nombre: "GRAND THEFT AUTO V",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/40.jpg",
    stock: 18,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 41,
    nombre: "Ghost of Tsushima",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/41.jpg",
    stock: 11,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 42,
    nombre: "HALF LIFE Alyx",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/42.jpg",
    stock: 19,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 43,
    nombre: "SIMS 4",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/43.jpg",
    stock: 36,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 44,
    nombre: "Returnal",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/44.jpg",
    stock: 35,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 45,
    nombre: "RESIDENT EVIL Village",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/45.jpg",
    stock: 30,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 46,
    nombre: "THE WITCHER Wild Hunt",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/46.jpg",
    stock: 45,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 47,
    nombre: "HORIZON Zero Dawn",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/47.jpg",
    stock: 12,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 48,
    nombre: "HALO Infinite",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/48.jpg",
    stock: 19,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 49,
    nombre: "Enter the Gungion",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/49.jpg",
    stock: 17,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 50,
    nombre: "LIFE IS STRANGE",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/50.jpg",
    stock: 54,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 51,
    nombre: "LIFE IS STRANGE True Colors",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/51.jpg",
    stock: 23,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 52,
    nombre: "HUMANKIND",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/52.jpg",
    stock: 45,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 53,
    nombre: "RESIDENT EVIL 2",
    creador: "",
    esrb: "",
    precio: "",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/53.jpg",
    stock: 23,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 54,
    nombre: "TOMB RAIDER",
    creador: "",
    esrb: "",
    precio: "316",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/54.jpg",
    stock: 36,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
  {
    id: 55,
    nombre: "SPIDER MAN Miles Morales",
    creador: "",
    esrb: "",
    precio: "250",
    imagen:
      "https://raw.githubusercontent.com/GiorgioCode/tienda-GameX/master/public/games-portadas/55.jpg",
    stock: 35,
    categoria: 1,
    tiempo: 72,
    puntuacion: 7.2,
    detalles: "",
    video: "",
  },
];
